/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsaRouteImport } from './routes/usa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportersRouteImport } from './routes/importers'
import { Route as EuRouteImport } from './routes/eu'
import { Route as ChinaRouteImport } from './routes/china'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiGetKeyRouteImport } from './routes/api/get-key'
import { Route as ApiCheckServiceRoleRouteImport } from './routes/api/check-service-role'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'

const UsaRoute = UsaRouteImport.update({
  id: '/usa',
  path: '/usa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportersRoute = ImportersRouteImport.update({
  id: '/importers',
  path: '/importers',
  getParentRoute: () => rootRouteImport,
} as any)
const EuRoute = EuRouteImport.update({
  id: '/eu',
  path: '/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinaRoute = ChinaRouteImport.update({
  id: '/china',
  path: '/china',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGetKeyRoute = ApiGetKeyRouteImport.update({
  id: '/api/get-key',
  path: '/api/get-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckServiceRoleRoute = ApiCheckServiceRoleRouteImport.update({
  id: '/api/check-service-role',
  path: '/api/check-service-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/china': typeof ChinaRoute
  '/eu': typeof EuRoute
  '/importers': typeof ImportersRoute
  '/login': typeof LoginRoute
  '/usa': typeof UsaRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/check-service-role': typeof ApiCheckServiceRoleRoute
  '/api/get-key': typeof ApiGetKeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/china': typeof ChinaRoute
  '/eu': typeof EuRoute
  '/importers': typeof ImportersRoute
  '/login': typeof LoginRoute
  '/usa': typeof UsaRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/check-service-role': typeof ApiCheckServiceRoleRoute
  '/api/get-key': typeof ApiGetKeyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/china': typeof ChinaRoute
  '/eu': typeof EuRoute
  '/importers': typeof ImportersRoute
  '/login': typeof LoginRoute
  '/usa': typeof UsaRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/check-service-role': typeof ApiCheckServiceRoleRoute
  '/api/get-key': typeof ApiGetKeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/china'
    | '/eu'
    | '/importers'
    | '/login'
    | '/usa'
    | '/admin/mfa'
    | '/api/check-service-role'
    | '/api/get-key'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/china'
    | '/eu'
    | '/importers'
    | '/login'
    | '/usa'
    | '/admin/mfa'
    | '/api/check-service-role'
    | '/api/get-key'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/china'
    | '/eu'
    | '/importers'
    | '/login'
    | '/usa'
    | '/admin/mfa'
    | '/api/check-service-role'
    | '/api/get-key'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChinaRoute: typeof ChinaRoute
  EuRoute: typeof EuRoute
  ImportersRoute: typeof ImportersRoute
  LoginRoute: typeof LoginRoute
  UsaRoute: typeof UsaRoute
  ApiCheckServiceRoleRoute: typeof ApiCheckServiceRoleRoute
  ApiGetKeyRoute: typeof ApiGetKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usa': {
      id: '/usa'
      path: '/usa'
      fullPath: '/usa'
      preLoaderRoute: typeof UsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importers': {
      id: '/importers'
      path: '/importers'
      fullPath: '/importers'
      preLoaderRoute: typeof ImportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu': {
      id: '/eu'
      path: '/eu'
      fullPath: '/eu'
      preLoaderRoute: typeof EuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/china': {
      id: '/china'
      path: '/china'
      fullPath: '/china'
      preLoaderRoute: typeof ChinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/get-key': {
      id: '/api/get-key'
      path: '/api/get-key'
      fullPath: '/api/get-key'
      preLoaderRoute: typeof ApiGetKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-service-role': {
      id: '/api/check-service-role'
      path: '/api/check-service-role'
      fullPath: '/api/check-service-role'
      preLoaderRoute: typeof ApiCheckServiceRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMfaRoute: typeof AdminMfaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMfaRoute: AdminMfaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChinaRoute: ChinaRoute,
  EuRoute: EuRoute,
  ImportersRoute: ImportersRoute,
  LoginRoute: LoginRoute,
  UsaRoute: UsaRoute,
  ApiCheckServiceRoleRoute: ApiCheckServiceRoleRoute,
  ApiGetKeyRoute: ApiGetKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
